excerpt_separator: <!--more-->
kramdown:
  math_engine: mathjax
defaults:
  -
    scope:
      path: "docs/math"
      type: "pages"
    values:
      layout: "mathdoc"
      permalink: /math/:basename:output_ext
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "note"
      permalink: /notes/:year/:month/:day/:title:output_ext
