version: '3.7'
services:
  app:
    image: jekyll/jekyll:pages
    command: jekyll serve --force_polling
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000